[C;!$(C[#7]);H2,H3:1]>>[C:1]NC(=O)C[SiH3]	Al_Cl
[C;H2,H3:1]>>[C:1]CNC(=O)C[SiH3]		Al_CCl
[c;H:1]>>[c:1]NC(=O)C[SiH3]			Ar_Cl
[c;H:1]>>[c:1]CNC(=O)C[SiH3]			Ar_CCl
[N;!$(NC=O);!H0:1]>>[N:1]C(=O)C[SiH3]		Am_Cl
[C;!$(C[#7]);H2,H3:1]>>[C:1]NC(=O)CC[SiH3]	Al_C
[C;H2,H3:1]>>[C:1]CNC(=O)CC[SiH3]		Al_CC
[c;H:1]>>[c:1]NC(=O)CC[SiH3]			Ar_C
[c;H:1]>>[c:1]CNC(=O)CC[SiH3]			Ar_CC
[N;!$(NC=O);!H0:1]>>[N:1]C(=O)CC[SiH3]		Am_C
[C;!$(C[#7]);H2,H3:1]>>[C:1]NS(=O)(=O)CC[SiH3]	Al_Sl
[C;H2,H3:1]>>[C:1]CNS(=O)(=O)CC[SiH3]		Al_CSl
[c;H:1]>>[c:1]NS(=O)(=O)CC[SiH3]		Ar_Sl
[c;H:1]>>[c:1]CNS(=O)(=O)CC[SiH3]		Ar_CSl
[N;!$(NC=O);!H0:1]>>[N:1]S(=O)(=O)CC[SiH3]	Am_Sl
[C;!$(C[#7]);H2,H3:1]>>[C:1]NC(=O)C=C[SiH3]     Al_C#
[C;H2,H3:1]>>[C:1]CNC(=O)C=C[SiH3]              Al_CC#
[c;H:1]>>[c:1]NC(=O)C=C[SiH3]                   Ar_C#
[c;H:1]>>[c:1]CNC(=O)C=C[SiH3]                  Ar_CC#
[N;!$(NC=O);!H0:1]>>[N:1]C(=O)C=C[SiH3]         Am_C#
