[C;!$(C[#7]);H2,H3:1]>>[C:1]NC(=O)C[SiH3]	aliphatic_Cl
[C;H2,H3:1]>>[C:1]CNC(=O)C[SiH3]		aliphatic_CCl
[c;H:1]>>[c:1]NC(=O)C[SiH3]			aromatic_Cl
[c;H:1]>>[c:1]CNC(=O)C[SiH3]			aromatic_CCl
[N;!$(NC=O);!H0:1]>>[N:1]C(=O)C[SiH3]		amine_Cl
[C;!$(C[#7]);H2,H3:1]>>[C:1]NC(=O)CC[SiH3]	aliphatic_CC
[C;H2,H3:1]>>[C:1]CNC(=O)CC[SiH3]		aliphatic_CCC
[c;H:1]>>[c:1]NC(=O)CC[SiH3]			aromatic_CC
[c;H:1]>>[c:1]CNC(=O)CC[SiH3]			aromatic_CCC
[N;!$(NC=O);!H0:1]>>[N:1]C(=O)CC[SiH3]		amine_CC
[C;!$(C[#7]);H2,H3:1]>>[C:1]NS(=O)(=O)CC[SiH3]	aliphatic_Sl
[C;H2,H3:1]>>[C:1]CNS(=O)(=O)CC[SiH3]		aliphatic_CSl
[c;H:1]>>[c:1]NS(=O)(=O)CC[SiH3]		aromatic_Sl
[c;H:1]>>[c:1]CNS(=O)(=O)CC[SiH3]		aromatic_CSl
[N;!$(NC=O);!H0:1]>>[N:1]S(=O)(=O)CC[SiH3]	amine_Sl
[C;!$(C[#7]);H2,H3:1]>>[C:1]NC(=O)C=C[SiH3]     aliphatic_C#C
[C;H2,H3:1]>>[C:1]CNC(=O)C=C[SiH3]              aliphatic_CC#C
[c;H:1]>>[c:1]NC(=O)C=C[SiH3]                   aromatic_C#C
[c;H:1]>>[c:1]CNC(=O)C=C[SiH3]                  aromatic_CC#C
[N;!$(NC=O);!H0:1]>>[N:1]C(=O)C=C[SiH3]         amine_C#C
